language: python
python:
- '3.5'
- 3.5-dev
- '3.6'
- 3.6-dev
- '3.7'
- 3.7-dev
- '3.8'
- 3.8-dev
env:
- GEVENT=true
- GEVENT=false
install:
- pip install gevent\<1.5.0 pytest-random-order
- |-
  if [[ $TRAVIS_PYTHON_VERSION = 3.4 ]]; then
    pip install PyYaml==5.2
  else
    pip install PyYaml
  fi
- pip install sphinx==1.7.9 ghp-import
before_script:
- export TZ=Asia/Jerusalem
script:
- python -m pytest --random-order-bucket=package -vv test_package.py
- python -m pytest --random-order-bucket=package -vv tests
- python -m pytest --random-order-bucket=package -vv --doctest-modules easypy
notifications:
  email:
    on_success: change
    on_failure: change
after_success: |-
  [[ $TRAVIS_JOB_NUMBER = *.1 ]] &&
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  sphinx-apidoc -o _static easypy &&
  PYTHONPATH=`pwd`:$PYTHONPATH sphinx-build -M html "." "_build" &&
  echo "<meta http-equiv=refresh content=0;url=html/_static/easypy.html>" > _build/index.html &&
  export PATH=$HOME/.local/bin:$PATH &&
  ghp-import -n _build &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
deploy:
  provider: pypi
  user: __token__
  password:
    secure: PPWP5YWgZxtRZck54RtS2dw5g3u1IrjaNVZLErqoONimIVq+Kn9CYZgAg/mZcmOUNYcG72Q/Y/00dY/hh9zC3jLMdcPssWRvJOaVvhJHZrCNlT/LO4XW8ZJ2H5bKFdRin+XLoz3QYjPQdXEc2QJoeP9/2ypa58oNYdbOo6mhqOSKWNNeLPeo6by84bg15heiSTVOE+vVVxuck+BxCympLDfZf0VMw1iEAtSpTmc0ICiP6qDzsVdKtbj4Za75fIDf1Ee41ZseVBkkSmDzBpPVHJmniivlNi5HRxPs0rZLvcBNWml5Mb8A2JZVgaUNpobh1kvGPNiBmkeVFO+31ZMPEyzLzSdZMJT/7Kz15S0rSfM4UjGsMsteg3hDWW+qm6/pQ8KH/Z9ej7SBB+2+vojdxUe31Vlp0LXvbltlR2T+94obpM67b7F+GFrfaKRwkhgbN79w4VPKiAvqk7l4suK74JwjzZmkxuDmqf38fiqdSXpY1T0aks4R/IlNbicbr3168dnmpKldKcZHtg9KzhjEvHPtsx0UUCAoZMA9aOy1AUkhkRFSAK38HykjTmYXkUBK04d9cNVTBnaFZhwmX70Q3D5NNG7aB/56u+mdRW+1i4go+Rtt4FHPIRN6fwLmdX9p7tPGWj4Tjm9FN87EcbPuhqdPMrr0rNFoDcG8aTAg0w0=
  on:
    tags: true
  skip_existing: true
